language: objective-c
matrix:
  include:
    - osx_image: xcode10.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace OpenInTerminal.xcworkspace -scheme OpenInTerminal -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO